name: NoCraft
version: 0.1
author: Taufiq Hoven
website: 
main: com.quiptiq.nocraft.NoCraft
description: Intercepts crafting events.
softdepend: [Spout]
commands:
    nc:
        description: "NoCraft commands"
        usage: |
            /nc allow <itemId>
            /nc disallow <itemId>
            /nc list
        aliases: []