name: ${project.name}
version: ${project.version}
author: ${project.author}
website: ${project.url}
main: com.quiptiq.incraftible.Incraftible
description: Intercepts crafting events.
depend: [Spout]
softdepend: [PermissionsBukkit]
commands:
    ic:
        description: "Incraftible commands"
        usage: |
            /ic logperms <loggedInPlayerName>
        aliases: []
permissions:
    incraftible.command.*:
        description: Gives access to all incraftible commands.
        default: op
        children:
            incraftible.command.logperms:   true
    incraftible.command.logperms:
        description: Allows access to the command that logs all permissions for a player.
        default: op
    incraftible.craft.unknown:
        description: Currently experimental. Allows crafting of materials that are not recognised by Incraftible. This means that plugin updates will only be required for explicit control of these materials.
        default: false
    incraftible.craft.*:
        description: Allows crafting of all items.
        default: false
        children:
            incraftible.craft.unknown:  true
    incraftible.craft.tools.*:
        description: Allows crafting of all tools.
        default: false
        children:
            incraftible.craft.tools.wood.*: true
            incraftible.craft.tools.stone.*:    true
            incraftible.craft.tools.gold.*: true
            incraftible.craft.tools.iron.*: true
            incraftible.craft.tools.diamond.*:  true
    incraftible.craft.tools.wood.*:
        description: Allows crafting of all wooden tools.
        default: false
        children:
            incraftible.craft.wood_sword: true
            incraftible.craft.wood_spade: true
            incraftible.craft.wood_pickaxe: true
            incraftible.craft.wood_axe: true
            incraftible.craft.wood_hoe: true
    incraftible.craft.tools.stone.*:
        description:    Allows crafting of stone tools.
        default: false
        children:
            incraftible.craft.stone_sword:  true
            incraftible.craft.stone_spade:  true
            incraftible.craft.stone_pickaxe:    true
            incraftible.craft.stone_axe:    true
            incraftible.craft.stone_hoe:    true
    incraftible.craft.tools.gold.*:
        description:    Allows crafting of gold tools.
        default: false
        children:
            incraftible.craft.gold_sword:  true
            incraftible.craft.gold_spade:  true
            incraftible.craft.gold_pickaxe:    true
            incraftible.craft.gold_axe:    true
            incraftible.craft.gold_hoe:    true
    incraftible.craft.tools.iron.*:
        description:    Allows crafting of iron tools.
        default: false
        children:
            incraftible.craft.iron_sword:  true
            incraftible.craft.iron_spade:  true
            incraftible.craft.iron_pickaxe:    true
            incraftible.craft.iron_axe:    true
            incraftible.craft.iron_hoe:    true
    incraftible.craft.tools.diamond.*:
        description:    Allows crafting of diamond tools.
        default: false
        children:
            incraftible.craft.diamond_sword:  true
            incraftible.craft.diamond_spade:  true
            incraftible.craft.diamond_pickaxe:    true
            incraftible.craft.diamond_axe:    true
            incraftible.craft.diamond_hoe:    true
    incraftible.craft.weapons.*:
        description:    Allows crafting of all weapons.
        default:    false
        children:
            incraftible.craft.wood_sword:   true
            incraftible.craft.stone_sword:   true
            incraftible.craft.gold_sword:   true
            incraftible.craft.iron_sword:   true
            incraftible.craft.diamond_sword:   true
            incraftible.craft.bow:  true
            incraftible.craft.arrow:    true
    incraftible.craft.armor.*:
        description:    Allows crafting of all armor.
        default:    false
        children:
            incraftible.craft.armor.leather.*:  true
            incraftible.craft.armor.iron.*:  true
            incraftible.craft.armor.diamond.*:  true
            incraftible.craft.armor.gold.*:  true
    incraftible.craft.armor.leather.*:
        description:    Allows crafting of all leather armor.
        default:    false
        children:
            incraftible.craft.leather_helmet: true
            incraftible.craft.leather_chestplate: true
            incraftible.craft.leather_leggings: true
            incraftible.craft.leather_boots: true
    incraftible.craft.armor.iron.*:
        description:    Allows crafting of all iron armor.
        default:    false
        children:
            incraftible.craft.iron_helmet: true
            incraftible.craft.iron_chestplate: true
            incraftible.craft.iron_leggings: true
            incraftible.craft.iron_boots: true
    incraftible.craft.armor.diamond.*:
        description:    Allows crafting of all diamond armor.
        default:    false
        children:
            incraftible.craft.diamond_helmet: true
            incraftible.craft.diamond_chestplate: true
            incraftible.craft.diamond_leggings: true
            incraftible.craft.diamond_boots: true
    incraftible.craft.armor.gold.*:
        description:    Allows crafting of all gold armor.
        default:    false
        children:
            incraftible.craft.gold_helmet: true
            incraftible.craft.gold_chestplate: true
            incraftible.craft.gold_leggings: true
            incraftible.craft.gold_boots: true
    incraftible.craft.standard:
        description: Allows crafting of all standard minecraft items. This is the default.
        default: false
        children:
            incraftible.craft.wood: true
            incraftible.craft.lapis_block: true
            incraftible.craft.dispenser: true
            incraftible.craft.sandstone: true
            incraftible.craft.note_block: true
            incraftible.craft.powered_rail: true
            incraftible.craft.detector_rail: true
            incraftible.craft.piston_sticky_base: true
            incraftible.craft.piston_base: true
            incraftible.craft.wool.*: true
            incraftible.craft.gold_block: true
            incraftible.craft.iron_block: true
            incraftible.craft.double_step: true
            incraftible.craft.step: true
            incraftible.craft.brick: true
            incraftible.craft.tnt: true
            incraftible.craft.bookshelf: true
            incraftible.craft.torch: true
            incraftible.craft.wood_stairs: true
            incraftible.craft.chest: true
            incraftible.craft.diamond_block: true
            incraftible.craft.workbench: true
            incraftible.craft.furnace: true
            incraftible.craft.sign_post: true
            incraftible.craft.wooden_door: true
            incraftible.craft.ladder: true
            incraftible.craft.rails: true
            incraftible.craft.cobblestone_stairs: true
            incraftible.craft.lever: true
            incraftible.craft.stone_plate: true
            incraftible.craft.wood_plate: true
            incraftible.craft.redstone_torch_on: true
            incraftible.craft.stone_button: true
            incraftible.craft.snow_block: true
            incraftible.craft.clay: true
            incraftible.craft.jukebox: true
            incraftible.craft.fence: true
            incraftible.craft.glowstone: true
            incraftible.craft.jack_o_lantern: true
            incraftible.craft.trap_door: true
            incraftible.craft.smooth_brick: true
            incraftible.craft.iron_fence: true
            incraftible.craft.thin_glass: true
            incraftible.craft.melon_block: true
            incraftible.craft.fence_gate: true
            incraftible.craft.brick_stairs: true
            incraftible.craft.smooth_stairs: true
            incraftible.craft.iron_spade: true
            incraftible.craft.iron_pickaxe: true
            incraftible.craft.iron_axe: true
            incraftible.craft.flint_and_steel: true
            incraftible.craft.bow: true
            incraftible.craft.arrow: true
            incraftible.craft.diamond: true
            incraftible.craft.iron_ingot: true
            incraftible.craft.gold_ingot: true
            incraftible.craft.iron_sword: true
            incraftible.craft.wood_sword: true
            incraftible.craft.wood_spade: true
            incraftible.craft.wood_pickaxe: true
            incraftible.craft.wood_axe: true
            incraftible.craft.stone_sword: true
            incraftible.craft.stone_spade: true
            incraftible.craft.stone_pickaxe: true
            incraftible.craft.stone_axe: true
            incraftible.craft.diamond_sword: true
            incraftible.craft.diamond_spade: true
            incraftible.craft.diamond_pickaxe: true
            incraftible.craft.diamond_axe: true
            incraftible.craft.stick: true
            incraftible.craft.bowl: true
            incraftible.craft.mushroom_soup: true
            incraftible.craft.gold_sword: true
            incraftible.craft.gold_spade: true
            incraftible.craft.gold_pickaxe: true
            incraftible.craft.gold_axe: true
            incraftible.craft.wood_hoe: true
            incraftible.craft.stone_hoe: true
            incraftible.craft.iron_hoe: true
            incraftible.craft.diamond_hoe: true
            incraftible.craft.gold_hoe: true
            incraftible.craft.bread: true
            incraftible.craft.leather_helmet: true
            incraftible.craft.leather_chestplate: true
            incraftible.craft.leather_leggings: true
            incraftible.craft.leather_boots: true
            incraftible.craft.iron_helmet: true
            incraftible.craft.iron_chestplate: true
            incraftible.craft.iron_leggings: true
            incraftible.craft.iron_boots: true
            incraftible.craft.diamond_helmet: true
            incraftible.craft.diamond_chestplate: true
            incraftible.craft.diamond_leggings: true
            incraftible.craft.diamond_boots: true
            incraftible.craft.gold_helmet: true
            incraftible.craft.gold_chestplate: true
            incraftible.craft.gold_leggings: true
            incraftible.craft.gold_boots: true
            incraftible.craft.painting: true
            incraftible.craft.golden_apple: true
            incraftible.craft.sign: true
            incraftible.craft.wood_door: true
            incraftible.craft.bucket: true
            incraftible.craft.minecart: true
            incraftible.craft.iron_door: true
            incraftible.craft.boat: true
            incraftible.craft.paper: true
            incraftible.craft.book: true
            incraftible.craft.storage_minecart: true
            incraftible.craft.powered_minecart: true
            incraftible.craft.compass: true
            incraftible.craft.fishing_rod: true
            incraftible.craft.watch: true
            incraftible.craft.dye.*: true
            incraftible.craft.sugar: true
            incraftible.craft.cake: true
            incraftible.craft.bed: true
            incraftible.craft.diode: true
            incraftible.craft.cookie: true
            incraftible.craft.map: true
            incraftible.craft.shears: true
            incraftible.craft.melon: true
            incraftible.craft.melon_seeds: true