name: NoCraft
version: 0.1
author: Taufiq Hoven
website: 
main: com.quiptiq.nocraft.NoCraft
description: Intercepts crafting events.
softdepend: [BukkitContrib, LogBlock]
commands:
    nc:
        description: "NoCraft commands"
        usage: "Usage: /nc allow|disallow <itemId>"
        aliases: []